# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJtRZM8IQanYn9fZsOSvAruFqX6NbJ0z
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
mean_1, mean_2, mean_3 = [2,2], [7,7], [4,10]
cov = [[1.0, 0.5], [0.5, 1.0]]
data_1 = np.random.multivariate_normal(mean_1, cov, 150)
data_2 = np.random.multivariate_normal(mean_2, cov, 200)
data_3 = np.random.multivariate_normal(mean_3, cov, 150)
X = np.vstack((data_1, data_2, data_3))

plt.scatter(X[:,0], X[:,1], s=10)
plt.title('Synthetic Clusters')
plt.xlabel("X1")
plt.ylabel("X2")
plt.show()

#implenment kmeans
def kmeans(X, k, max_iters=100, tol=1e-4):
    n, d = X.shape
    centroids = X[np.random.choice(n, k, replace=False)]
    prev_centroids = centroids.copy()
    for _ in range(max_iters):
        distances = np.linalg.norm(X[:, None] - centroids, axis=2)
        labels = np.argmin(distances, axis=1)
        centroids = np.array([X[labels == i].mean(axis=0) for i in range(k)])
        if np.all(np.abs(centroids - prev_centroids) < tol):
            break
        prev_centroids = centroids.copy()
    return labels, centroids

labels, centroids = kmeans(X, 3)

#eblow method
inertias = []
K_range = range(1, 11)
for k in K_range:
    labels, centroids = kmeans(X, k)
    inertia = np.sum((X - centroids[labels]) ** 2)
    inertias.append(inertia)

plt.plot(K_range, inertias, marker='o')
plt.xlabel('Number of clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()

#final clustering and comparsion
from sklearn.cluster import KMeans

optimal_k = 3 # replace with elbow result value if needed
my_labels, _ = kmeans(X, optimal_k)
sk = KMeans(n_clusters=optimal_k, random_state=42).fit(X)
sk_labels = sk.labels_

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.scatter(X[:,0], X[:,1], c=my_labels)
plt.title('Custom K-Means')
plt.subplot(1,2,2)
plt.scatter(X[:,0], X[:,1], c=sk_labels)
plt.title('scikit-learn KMeans')
plt.show()

"""Project Analysis:

How data was created: Used NumPy to generate random 2D clusters.

Optimal K: Determined using the Elbow Method; selected K=3 due to the clear elbow in the inertia plot.

Comparison: Both methods provided similar clusters; scikit-learn is faster and optimized for large data, but custom method works well and is transparent.

How to Run

  Install dependencies:

       pip install numpy matplotlib scikit-learn

  Save code into .py or Jupyter notebook.

  Run each cell step by step.

  Results will display as plots and visual comparisons.
"""